api_platform:
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    show_webby: false
    swagger:
        api_keys:
            api_token:
                name: x-api-token
                type: header
    version: '%env(resolve:VERSION)%'
